### ISSUE TITLE
【Migration Feature】Shortcut

### ISSUE THREAD

**Issue by feloxx** [vnotex/vnote#2090]
# Shortcut

Move most of the commonly used shortcut keys in vnote 2 to vnote 3, and this issue can also collect shortcut key related requirements (reply directly).

> For example, in the list of notes, `note copy` and `note paste` can only be clicked. After achieving the shortcut keys, you can use `Ctrl + C` and `Ctrl + V`.
> The shortcut keys can be replaced at will in the user profile.

Feature that have been merged will appear in the continuous-build: [download](https://github.com/vnotex/vnote/releases/tag/continuous-build)

# Implement the list

- [x] Copy `Ctrl + C` #2088 #2096 
- [x] Paste `Ctrl + V` #2088 #2096 
- [x] Cut `Ctrl + X` #2100 
- [x] New Note `Ctrl + Alt + N` #2101 
- [x] New Folder `Ctrl + Alt + S` #2101 
- [x] Properties `F2` #2094 #2096 
- [x] Global_WakeUp `Ctrl+Alt+U` #2097 
- [x] CloseAllTabs `""` #2173 
- [x] CloseOtherTabs `""` #2173 
- [x] CloseTabsToTheLeft `""` #2173 
- [x] CloseTabsToTheRight `""` #2173 
- [x] Positioning of notes `Ctrl+G, D`
- [x] ~~Real-time preview~~
- [x] Paste for markdown #2277
